spring.application.name=jjoncketing

# Scheduler
scheduler.dessert-open.enabled=true

# Firebase
firebase.service-account-key=classpath:firebase/service-account.json

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379

# Redis Stream
redis.stream.fcm.consumer-group=fcm-notification-group
redis.stream.fcm.consumer-name=fcm-consumer-1
redis.stream.fcm.max-retry=3
redis.stream.fcm.dlq-key=fcm:notification:dlq
redis.stream.fcm.failures-key=fcm:message:failures
